### PR TITLE
feat: adds backend files to project

### PR DESCRIPTION
**Pull request by RichHawkins**

### CODE REVIEW

**Review by NatayaP — APPROVED** [review]
LGTM

**Review by anthonydmays — COMMENTED** [review]
You should definitely add `node_modules` to your `.gitignore` file. We usually avoid checking that in.

**Comment by RichHawkins** [comment]
@anthonydmays Hmm, I didn't realize they got checked in, it was already in my .gitignore file.

**Comment by anthonydmays** [comment]
> @anthonydmays Hmm, I didn't realize they got checked in, it was already in my .gitignore file. 
> 
> 
> 

There's a way to delete from GH but keep local. Or you could just delete local, commit, then run npm install again to get packages back.

**Pull request merged**
